#~~~~███████╗██╗~~██╗██████╗~██╗~~~██╗██████╗~
#~~~~██╔════╝╚██╗██╔╝██╔══██╗██║~~~██║██╔══██╗
#~~~~█████╗~~~╚███╔╝~██████╔╝██║~~~██║██████╔╝
#~~~~██╔══╝~~~██╔██╗~██╔═══╝~╚██╗~██╔╝██╔═══╝~
#~~~~███████╗██╔╝~██╗██║~~~~~~╚████╔╝~██║~~~~~
#~~~~╚══════╝╚═╝~~╚═╝╚═╝~~~~~~~╚═══╝~~╚═╝~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Expvp Minecraft Game Mode
override-xlogin-spawn-command-because-bukkits-command-handling-sucks: true
