#~~~~███████╗██╗~~██╗██████╗~██╗~~~██╗██████╗~
#~~~~██╔════╝╚██╗██╔╝██╔══██╗██║~~~██║██╔══██╗
#~~~~█████╗~~~╚███╔╝~██████╔╝██║~~~██║██████╔╝
#~~~~██╔══╝~~~██╔██╗~██╔═══╝~╚██╗~██╔╝██╔═══╝~
#~~~~███████╗██╔╝~██╗██║~~~~~~╚████╔╝~██║~~~~~
#~~~~╚══════╝╚═╝~~╚═╝╚═╝~~~~~~~╚═══╝~~╚═╝~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ExPvP Minecraft Game Mode
# Copyright (C) 2016 Literallie / Philipp Nowak.
# Please see the LICENSE.txt file included in the plugin jar.
#
# Do not forget to configure credentials below.

sql:
  host: jdbc:mysql://localhost:3306/
  database: mt_main
  user: expvp
  password: 'Please enter a secure database password'
